from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path


def read_version(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def parse_args() -> argparse.Namespace:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="Publish built release artifacts into a static update directory."
    )
    parser.add_argument(
        "--platform",
        required=True,
        choices=("windows", "macos"),
        help="Release platform to publish.",
    )
    parser.add_argument(
        "--public-root",
        required=True,
        help="Static files root directory exposed by your update server.",
    )
    parser.add_argument(
        "--release-dir",
        default=str(root / "release"),
        help="Local release directory generated by the build script.",
    )
    parser.add_argument(
        "--version",
        default="",
        help="Release version. Defaults to app_version.txt.",
    )
    parser.add_argument(
        "--version-file",
        default=str(root / "app_version.txt"),
        help="Version file path.",
    )
    parser.add_argument(
        "--assets-subdir",
        default="releases",
        help="Subdirectory under public root used to store versioned assets.",
    )
    return parser.parse_args()


def ensure_file(path: Path) -> Path:
    if not path.exists():
        raise SystemExit(f"Required file not found: {path}")
    return path


def copy_file(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)


def resolve_windows_assets(release_dir: Path, version: str) -> tuple[Path, list[Path]]:
    manifest = ensure_file(release_dir / "latest.json")
    installer = ensure_file(release_dir / f"AIBossWorkbench-Windows-Installer-v{version}.exe")
    assets = [installer]
    zip_path = release_dir / f"AIBossWorkbench-Windows-v{version}.zip"
    if zip_path.exists():
        assets.append(zip_path)
    return manifest, assets


def resolve_macos_assets(release_dir: Path, version: str) -> tuple[Path, list[Path]]:
    manifest = ensure_file(release_dir / "latest-macos.json")
    zip_path = ensure_file(release_dir / f"AIBossWorkbench-macOS-v{version}.zip")
    assets = [zip_path]
    dmg_path = release_dir / f"AIBossWorkbench-macOS-v{version}.dmg"
    if dmg_path.exists():
        assets.append(dmg_path)
    extra_patterns = (
        f"AIBossWorkbench-macOS-v{version}-*.zip",
        f"AIBossWorkbench-macOS-v{version}-*.dmg",
    )
    for pattern in extra_patterns:
        for path in sorted(release_dir.glob(pattern)):
            if path not in assets:
                assets.append(path)
    return manifest, assets


def main() -> int:
    args = parse_args()
    version = (args.version or "").strip()
    if not version:
        version = read_version(Path(args.version_file).expanduser().resolve())
    if not version:
        raise SystemExit("Version is empty.")

    release_dir = Path(args.release_dir).expanduser().resolve()
    public_root = Path(args.public_root).expanduser().resolve()
    version_root = public_root / args.assets_subdir / version

    if args.platform == "windows":
        manifest, assets = resolve_windows_assets(release_dir, version)
        manifest_name = "latest.json"
    else:
        manifest, assets = resolve_macos_assets(release_dir, version)
        manifest_name = "latest-macos.json"

    version_root.mkdir(parents=True, exist_ok=True)
    for asset in assets:
        copy_file(asset, version_root / asset.name)

    copy_file(manifest, version_root / manifest_name)
    copy_file(manifest, public_root / manifest_name)

    payload = {
        "platform": args.platform,
        "version": version,
        "public_root": str(public_root),
        "version_root": str(version_root),
        "manifest": str(public_root / manifest_name),
        "assets": [str(version_root / asset.name) for asset in assets],
    }
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
